### ISSUE TITLE
Update issue on Julia v0.6.0 on os x

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/Ipopt.jl#105] opened 2018-03-15 02:54 UTC
I had an odd issue where doing an update on Julia v0.6.0 on os x lead to the error messages below.  Updating the v0.6.2 seemed to resolve the issue.

```
WARNING: imported binding for srcdir overwritten in module __anon__
Info: Downloading https://github.com/staticfloat/IpoptBuilder/releases/download/v3.12.8-9/Ipopt.x86_64-apple-darwin14.tar.gz to /Users/carleton/.julia/v0.6/Ipopt/deps/usr/downloads/Ipopt.x86_64-apple-darwin14.tar.gz...
===========================================================[ ERROR: Ipopt ]===========================================================

LoadError: BinaryProvider.LibraryProduct("/Users/carleton/.julia/v0.6/Ipopt/deps/usr/lib", String["libipopt"], :libipopt, "Prefix(/Users/carleton/.julia/v0.6/Ipopt/deps/usr)") is not satisfied, cannot generate deps.jl!
while loading /Users/carleton/.julia/v0.6/Ipopt/deps/build.jl, in expression starting on line 13

======================================================================================================================================

===========================================================[ BUILD ERRORS ]===========================================================

WARNING: Ipopt had build errors.

 - packages with build errors remain installed in /Users/carleton/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Ipopt")`
 - build a single package by running its `deps/build.jl` script

======================================================================================================================================

julia> Pkg.test("Ipopt")
INFO: Testing Ipopt
ERROR: LoadError: UndefVarError: use_BinaryProvider not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /Users/carleton/.julia/v0.6/Ipopt/src/Ipopt.jl, in expression starting on line 11
ERROR: LoadError: Failed to precompile Ipopt to /Users/carleton/.julia/lib/v0.6/Ipopt.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:456
 [3] require(::Symbol) at ./loading.jl:398
 [4] include_from_node1(::String) at ./loading.jl:569
 [5] include(::String) at ./sysimg.jl:14
 [6] process_options(::Base.JLOptions) at ./client.jl:305
 [7] _start() at ./client.jl:371
while loading /Users/carleton/.julia/v0.6/Ipopt/test/runtests.jl, in expression starting on line 1
===========================================================[ ERROR: Ipopt ]===========================================================

failed process: Process(`/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/carleton/.julia/v0.6/Ipopt/test/runtests.jl`, ProcessExited(1)) [1]

======================================================================================================================================
ERROR: Ipopt had test errors
```

**Comment by tkelman** [comment] 2018-03-15 02:57
Hm, what gfortran versions were the mac binaries of 0.6.0 and 0.6.1 built with? should possibly do a mac-only higher minimum julia requirement

**Comment by floswald** [comment] 2018-03-21 21:47
same here.

**Comment by floswald** [comment] 2018-03-21 21:54
and yes, updating julia to 0.6.2 solves this. not sure this is actually an issue in this case.

**Comment by ccoffrin** [comment] 2018-03-31 02:49
I don't know if this is the same issue, but worth noting that this Travis build is having trouble installing Ipopt v0.3.0 on OS X

https://travis-ci.org/lanl-ansi/PowerModelsAnnex.jl/builds/360509583

**Comment by mlubin** [comment] 2018-03-31 13:16
@ccoffrin, I saw that error sporadically before the recent changes. No idea what the issue is but looks like it's within BinDeps. I'll be happy when we can drop that dependency.

**Comment by ccoffrin** [comment] 2018-04-01 22:34
This build issue seems to have resolved it self.

**Comment by odow** [comment] 2019-02-16 00:41
Closing since the minimum Julia version is now 0.7 and we use BinaryProvider on all platforms.

**Closed by odow** 2019-02-16 00:41 UTC
