### ISSUE TITLE
Getting ReadOnlyMemoryError

### ISSUE THREAD

**Issue by mdpradeep** [JuliaOpt/Ipopt.jl#77] opened 2016-12-13 06:28 UTC
I am getting the following error with the new version.

```
julia> Pkg.test("Ipopt")
INFO: Testing Ipopt
ERROR: LoadError: LoadError: ReadOnlyMemoryError()
 in solveProblem(::Ipopt.IpoptProblem) at C:\Users\julia\AppData\Local\JuliaPro-
0.5.0.2\pkgs-0.5.0.2\v0.5\Ipopt\src\Ipopt.jl:304
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\julia\AppData\Local\JuliaPro-0.5.0.2\pkgs-0.5.0.2\v0.5\Ip
opt\test\hs071_test.jl, in expression starting on line 118
while loading C:\Users\julia\AppData\Local\JuliaPro-0.5.0.2\pkgs-0.5.0.2\v0.5\Ip
opt\test\runtests.jl, in expression starting on line 5
================================[ ERROR: Ipopt ]================================


failed process: Process(`'C:\Users\julia\AppData\Local\JuliaPro-0.5.0.2\Julia-0.
5.0\bin\julia' -Cx86-64 '-JC:\Users\julia\AppData\Local\JuliaPro-0.5.0.2\Julia-0
.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-co
verage=none --color=yes --compilecache=yes 'C:\Users\julia\AppData\Local\JuliaPr
o-0.5.0.2\pkgs-0.5.0.2\v0.5\Ipopt\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================

ERROR: Ipopt had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:74
0
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array
{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{Abstract
String,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{Abstra
ctString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::V
ararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::A
rray{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:25
8
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
```

**Version**:
```
julia> Pkg.status("Ipopt")
 - Ipopt                         0.2.6
```

**Comment by mlubin** [comment] 2016-12-14 03:49
CC @abelsiqueira (the only change of substance between 0.2.5 and 0.2.6)

**Comment by abelsiqueira** [comment] 2016-12-14 11:26
Hello @mdpradeep, can you show the tests on 0.2.5?

**Comment by joaquimg** [comment] 2016-12-15 14:38
I had the same error installing a Ipopt.jl in a brand new Windows computed yesterday, (no problems in MAC, haven´t tested on linux)

However I updated my old computer´s Ipopt and it still worked.

@abelsiqueira I tested checking out a different version of Ipopt.jl to run the test and the result is the same above.

It does not seem to be a julia issue, because the (only) fix to the problem was copying the WinRPM deps (which include ipopt executable) from the old computed to the new one.

I think the issue is related to either WinRPM or the Ipopt executable.

**Comment by mlubin** [comment] 2016-12-15 14:49
CC @tkelman

**Comment by mdpradeep** [comment] 2016-12-15 14:53
Thanks @joaquimg. On my system earlier versions are failing as well. The earlier versions were working on the same system before. As you mentioned it might be a WinRPM issue.

**Comment by tkelman** [comment] 2016-12-15 15:04
@mlubin I'm watching this repo, no need to ping specifically.

We should try turning up the print level in the ipopt options, and/or adding some debug output to the user-defined functions to see exactly where this is happening.

**Comment by mdpradeep** [comment] 2016-12-16 07:16
The parameter passed to the C call is:
```
prob = Ipopt.IpoptProblem(Ptr{Void} @0x0000000007271000,4,2,[1.0,5.0,5.0,1.0],[0
.0,0.0],[0.0,0.0],[0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0],0.0,0,eval_f,eval_g,eval_g
rad_f,eval_jac_g,eval_h,nothing,:Min)
```

The ccall made is:
```
ret = ccall((:IpoptSolve, libipopt),
    Cint, (Ptr{Void}, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}, Any),
    prob.ref, prob.x, prob.g, final_objval, prob.mult_g, prob.mult_x_L, prob.mult_x_U, prob)
```
https://github.com/JuliaOpt/Ipopt.jl/blob/master/src/Ipopt.jl#L304
Let me know if you need any more information.

**Comment by xximranxx** [comment] 2016-12-20 13:31
Just fyi, I also have the exact same issue on Windows 7, installed Ipopt today with newest julia release (0.5.0)

**Comment by mlubin** [comment] 2016-12-22 15:47
CCing @yuyichao @ihnorton @vtjnash who may have a better idea of what could cause the ``ReadOnlyMemoryError()`` from the ccall.

**Comment by mlubin** [comment] 2016-12-22 16:31
I've reproduced the issue locally on both Julia 0.4 and 0.5, so something has certainly changed in the WinRPM binaries.

**Comment by xximranxx** [comment] 2017-01-05 15:30
Just bumping...
Is there any idea how I could at least temporarily get Ipopt to work?
I am on the verge of convincing my employer to adopt julia and I need to demonstrate Ipopt for this
Thanks for any help

**Comment by mlubin** [comment] 2017-01-05 15:32
The most effective solution at this point would be to contact Julia Computing for professional support, since they have the expertise to fix this issue.

**Comment by ihnorton** [comment] 2017-01-16 06:33
stack trace:

![image](https://cloud.githubusercontent.com/assets/327706/21972884/b0158246-db8a-11e6-875b-6f37c66ad53f.png)

**Comment by tkelman** [comment] 2017-01-20 14:07
It's because opensuse changed threading models. In my local testing it looks like https://github.com/JuliaLang/julia/issues/20152 should fix this.

**Comment by tyleransom** [comment] 2017-01-31 15:31
@xximranxx If you only need to demonstrate something, you might consider using [JuliaBox](juliabox.com) to run some simple examples. That's Linux-based, so there's no issue with `Ipopt` at the moment. (I am putting together a short demo for a class and just a moment ago was able to successfully run a simple maximum likelihood estimator on JuliaBox.)

Regarding the previous comment by @tkelman, is this opensuse issue going to be resolved in 0.6, or somewhere else?

**Comment by tkelman** [comment] 2017-01-31 20:09
should already work on nightly. I have a PR over at WinRPM that would do the dll replacement for you: https://github.com/JuliaPackaging/WinRPM.jl/issues/97 you just might need to restart Julia.

If you copy all of the gcc dlls from winrpm and replace them in julia's bin folder yourself it should also work, see https://github.com/JuliaLang/julia/pull/20152#issuecomment-276258937

**Comment by davidanthoff** [comment] 2017-02-14 22:31
Is there a plan to fix this for current julia 0.5 users? This is quite a serious issue, essentially Ipopt has not been working on Windows for two months now, right?

**Comment by tkelman** [comment] 2017-02-14 22:35
try the branch at https://github.com/JuliaPackaging/WinRPM.jl/pull/97

**Comment by sylvaticus** [comment] 2017-02-16 14:09
@davidanthoff  I confirm that manually moving the dll worked (Win7/Julia 0.5).
In my case I did move all the dlls
from: C:\Users\[yourname]\.julia\v0.5\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin
to: C:\Users\[yourname]\AppData\Local\Julia-0.5.0\bin
(it should be enought to move just the dll indicated by @tkelman in its [JuliaLang/julia#20152 comment](https://github.com/JuliaLang/julia/pull/20152#issuecomment-276258937) )

**Comment by davidanthoff** [comment] 2017-02-20 20:46
@tkelman I'm hesitant to try that WinRPM branch, I have very little time this semester and that branch replaces stuff in my julia folder, right? I don't want to risk messing up my system right now. I was, I guess, more generally hoping for a fix that "just works", i.e. some new tagged releases for all the involved packages where my students can just do ``Pkg.add("Ipopt")`` and be done... Obviously totally understand that this might not be trivial.

**Comment by tkelman** [comment] 2017-02-23 14:20
The fix that just works is replacing Julia's gcc dll's. You can try the other way around but that's less likely to work.

**Comment by davidanthoff** [comment] 2017-02-23 17:35
Yeah, I fear that doesn't help me right now... I'm teaching a class using this and I know for sure that if I ask students to start replacing julia's gcc dlls I will just cause more problems ;) I guess it is juliabox for now.

**Comment by tkelman** [comment] 2017-02-23 21:09
the point of https://github.com/JuliaPackaging/WinRPM.jl/pull/97 is to do it automatically, if enough people test that and confirm whether it works.

0.5.1 should get the fix backported

**Comment by tyleransom** [comment] 2017-02-27 20:36
I second @sylvaticus's procedure. Worked like a charm for me! (N.B. I copied the DLLs instead of moving them)

**Comment by tkelman** [comment] 2017-03-06 05:32
Should be fixed in 0.5.1.

**Comment by mlubin** [comment] 2017-03-06 16:19
Thanks, @tkelman! I'll close this. If there are remaining problems, please open a new issue.

**Closed by mlubin** 2017-03-06 16:19 UTC

**Comment by tkelman** [comment] 2017-03-28 18:21
In case anyone else still hits this (as reported on discourse at https://discourse.julialang.org/t/readonlymemoryerror-using-ipopt-not-fixed-in-0-51/), WinRPM doesn't auto-upgrade existing installed binaries so you may need to run something like
```julia
using WinRPM
pkgs = String[]
for pkg in eachline(WinRPM.installedlist)
    name = match(Regex("$(WinRPM.OS_ARCH)-(.*)"), last(split(pkg)))
    if name !== nothing && !isempty(WinRPM.lookup(name[1]))
        push!(pkgs, name[1])
    end
end
WinRPM.install(pkgs)
```
to force it to download new copies.
